-- STRATELOQ DR: production public FOREIGN KEY constraints (schema baseline). NO data, NO secrets.
-- For full-data restore these validate normally. For sparse representative-data restore into the DR
-- project they are applied with NOT VALID (structure recovered without re-checking existing rows).
ALTER TABLE public.activation_authorizations ADD CONSTRAINT activation_authorizations_authority_id_fkey FOREIGN KEY (authority_id) REFERENCES marketing_spend_authority(id) ON DELETE SET NULL;
ALTER TABLE public.ad_studio_angles ADD CONSTRAINT ad_studio_angles_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES ad_studio_briefs(id) ON DELETE CASCADE;
ALTER TABLE public.ad_studio_assets ADD CONSTRAINT ad_studio_assets_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES ad_studio_briefs(id) ON DELETE CASCADE;
ALTER TABLE public.ad_studio_offers ADD CONSTRAINT ad_studio_offers_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES ad_studio_briefs(id) ON DELETE CASCADE;
ALTER TABLE public.ad_studio_platform_variants ADD CONSTRAINT ad_studio_platform_variants_angle_id_fkey FOREIGN KEY (angle_id) REFERENCES ad_studio_angles(id) ON DELETE CASCADE;
ALTER TABLE public.ad_studio_static_creatives ADD CONSTRAINT ad_studio_static_creatives_angle_id_fkey FOREIGN KEY (angle_id) REFERENCES ad_studio_angles(id) ON DELETE CASCADE;
ALTER TABLE public.analytics_events ADD CONSTRAINT analytics_events_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.analytics_events ADD CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.auth_event ADD CONSTRAINT auth_event_member_id_fkey FOREIGN KEY (member_id) REFERENCES member(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.business_profiles ADD CONSTRAINT business_profiles_application_id_fkey FOREIGN KEY (application_id) REFERENCES founding_applications(id) ON DELETE RESTRICT;
ALTER TABLE public.business_profiles ADD CONSTRAINT business_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_destination_choice ADD CONSTRAINT commerce_destination_choice_store_connection_id_fkey FOREIGN KEY (store_connection_id) REFERENCES commerce_store_connections(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_prediction_snapshots ADD CONSTRAINT commerce_prediction_snapshots_product_id_fkey FOREIGN KEY (product_id) REFERENCES commerce_products(id);
ALTER TABLE public.commerce_prediction_snapshots ADD CONSTRAINT commerce_prediction_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_member_opportunity_id_fkey FOREIGN KEY (member_opportunity_id) REFERENCES member_opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_product_id_fkey FOREIGN KEY (product_id) REFERENCES commerce_products(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_product_id_fkey FOREIGN KEY (product_id) REFERENCES commerce_products(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_store_connection_id_fkey FOREIGN KEY (store_connection_id) REFERENCES commerce_store_connections(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_product_id_fkey FOREIGN KEY (product_id) REFERENCES commerce_products(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.commerce_store_projects ADD CONSTRAINT commerce_store_projects_product_page_id_fkey FOREIGN KEY (product_page_id) REFERENCES commerce_product_pages(id) ON DELETE CASCADE;
ALTER TABLE public.communication_logs ADD CONSTRAINT communication_logs_application_id_fkey FOREIGN KEY (application_id) REFERENCES founding_applications(id) ON DELETE SET NULL;
ALTER TABLE public.communication_logs ADD CONSTRAINT communication_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.competitor_content ADD CONSTRAINT competitor_content_competitor_id_fkey FOREIGN KEY (competitor_id) REFERENCES competitors(id) ON DELETE CASCADE;
ALTER TABLE public.competitors ADD CONSTRAINT competitors_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.conversion_template_families ADD CONSTRAINT conversion_template_families_hero_variant_fkey FOREIGN KEY (hero_variant) REFERENCES conversion_hero_variants(variant);
ALTER TABLE public.daily_briefs ADD CONSTRAINT daily_briefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.demo_events ADD CONSTRAINT demo_events_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_member_id_fkey FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE;
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.discovery_state ADD CONSTRAINT discovery_state_member_id_fkey FOREIGN KEY (member_id) REFERENCES member(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.engagement_patterns ADD CONSTRAINT engagement_patterns_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.generated_content ADD CONSTRAINT generated_content_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.generated_content ADD CONSTRAINT generated_content_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.growth_messages ADD CONSTRAINT growth_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.invitation ADD CONSTRAINT invitation_application_ref_fkey FOREIGN KEY (application_ref) REFERENCES founding_applications(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.invitation ADD CONSTRAINT invitation_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES invitation(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.market_price_observations ADD CONSTRAINT market_price_observations_product_id_fkey FOREIGN KEY (product_id) REFERENCES commerce_products(id) ON DELETE SET NULL;
ALTER TABLE public.marketing_campaign_drafts ADD CONSTRAINT marketing_campaign_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.marketing_campaign_executions ADD CONSTRAINT marketing_campaign_executions_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES marketing_campaign_drafts(id) ON DELETE CASCADE;
ALTER TABLE public.media_assets ADD CONSTRAINT media_assets_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES media_assets(id) ON DELETE SET NULL;
ALTER TABLE public.media_video_jobs ADD CONSTRAINT media_video_jobs_source_image_asset_id_fkey FOREIGN KEY (source_image_asset_id) REFERENCES media_assets(id) ON DELETE SET NULL;
ALTER TABLE public.media_video_scenes ADD CONSTRAINT media_video_scenes_video_job_id_fkey FOREIGN KEY (video_job_id) REFERENCES media_video_jobs(id) ON DELETE CASCADE;
ALTER TABLE public.member ADD CONSTRAINT member_application_ref_fkey FOREIGN KEY (application_ref) REFERENCES founding_applications(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.member ADD CONSTRAINT member_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_member_opportunity_id_fkey FOREIGN KEY (member_opportunity_id) REFERENCES member_opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.member_business_dna ADD CONSTRAINT member_business_dna_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.member_business_dna ADD CONSTRAINT member_business_dna_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.member_feedback ADD CONSTRAINT member_feedback_content_id_fkey FOREIGN KEY (content_id) REFERENCES member_generated_content(id) ON DELETE SET NULL;
ALTER TABLE public.member_feedback ADD CONSTRAINT member_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.member_generated_content ADD CONSTRAINT member_generated_content_member_opportunity_id_fkey FOREIGN KEY (member_opportunity_id) REFERENCES member_opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.member_generated_content ADD CONSTRAINT member_generated_content_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.opportunities ADD CONSTRAINT opportunities_trend_cluster_id_fkey FOREIGN KEY (trend_cluster_id) REFERENCES trend_clusters(id) ON DELETE SET NULL;
ALTER TABLE public.pending_in_app_messages ADD CONSTRAINT pending_in_app_messages_message_id_fkey FOREIGN KEY (message_id) REFERENCES growth_messages(id) ON DELETE CASCADE;
ALTER TABLE public.pending_in_app_messages ADD CONSTRAINT pending_in_app_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.product_acquisitions ADD CONSTRAINT product_acquisitions_generated_content_id_fkey FOREIGN KEY (generated_content_id) REFERENCES member_generated_content(id) ON DELETE SET NULL;
ALTER TABLE public.product_acquisitions ADD CONSTRAINT product_acquisitions_source_run_id_fkey FOREIGN KEY (source_run_id) REFERENCES discovery_runs(id) ON DELETE CASCADE;
ALTER TABLE public.product_acquisitions ADD CONSTRAINT product_acquisitions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.rejected_ideas ADD CONSTRAINT rejected_ideas_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.rejected_ideas ADD CONSTRAINT rejected_ideas_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.saved_opportunities ADD CONSTRAINT saved_opportunities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
ALTER TABLE public.saved_opportunities ADD CONSTRAINT saved_opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.spend_reservations ADD CONSTRAINT spend_reservations_authority_id_fkey FOREIGN KEY (authority_id) REFERENCES marketing_spend_authority(id) ON DELETE CASCADE;
ALTER TABLE public.successful_opportunities ADD CONSTRAINT successful_opportunities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
ALTER TABLE public.successful_opportunities ADD CONSTRAINT successful_opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_consent ADD CONSTRAINT user_consent_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_events ADD CONSTRAINT user_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_growth_profile ADD CONSTRAINT user_growth_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_memory ADD CONSTRAINT user_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
