-- STRATELOQ DR: production public PRIMARY KEY + UNIQUE constraints (schema baseline). NO data, NO secrets.
ALTER TABLE public.activation_authorizations ADD CONSTRAINT activation_auth_idem UNIQUE (campaign_id, idempotency_key);
ALTER TABLE public.ad_studio_angles ADD CONSTRAINT ad_studio_angles_brief_id_angle_index_key UNIQUE (brief_id, angle_index);
ALTER TABLE public.ad_studio_platform_variants ADD CONSTRAINT ad_studio_platform_variants_angle_id_platform_placement_key UNIQUE (angle_id, platform, placement);
ALTER TABLE public.cj_sourcing_requests ADD CONSTRAINT cj_sourcing_requests_source_id_key UNIQUE (source_id);
ALTER TABLE public.commerce_destination_choice ADD CONSTRAINT commerce_destination_choice_user_id_key UNIQUE (user_id);
ALTER TABLE public.commerce_events ADD CONSTRAINT commerce_events_idem UNIQUE (tenant_id, event_id);
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_unique UNIQUE (user_id, product_id, source_run_id);
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_identity_unique UNIQUE (user_id, product_identity);
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_dedup_unique UNIQUE (user_id, dedup_key);
ALTER TABLE public.commerce_supplier_products ADD CONSTRAINT commerce_supplier_products_source_source_product_id_key UNIQUE (source, source_product_id);
ALTER TABLE public.commerce_tracking_identities ADD CONSTRAINT commerce_tracking_identities_tenant_id_pulse_tid_key UNIQUE (tenant_id, pulse_tid);
ALTER TABLE public.competitor_content ADD CONSTRAINT competitor_content_url_key UNIQUE (url);
ALTER TABLE public.conversion_dispatch_ledger ADD CONSTRAINT conversion_dispatch_ledger_idem UNIQUE (tenant_id, provider, event_id);
ALTER TABLE public.daily_briefs ADD CONSTRAINT daily_briefs_user_id_date_key UNIQUE (user_id, date);
ALTER TABLE public.discovery_state ADD CONSTRAINT discovery_state_member_id_unique UNIQUE (member_id);
ALTER TABLE public.fx_rates ADD CONSTRAINT fx_rates_uq UNIQUE (base_currency, quote_currency, as_of);
ALTER TABLE public.invitation ADD CONSTRAINT invitation_token_hash_unique UNIQUE (token_hash);
ALTER TABLE public.marketing_campaign_executions ADD CONSTRAINT marketing_campaign_executions_idem UNIQUE (draft_id, platform);
ALTER TABLE public.media_providers ADD CONSTRAINT media_providers_name_key UNIQUE (name);
ALTER TABLE public.media_video_scenes ADD CONSTRAINT media_video_scenes_video_job_id_scene_number_key UNIQUE (video_job_id, scene_number);
ALTER TABLE public.member ADD CONSTRAINT member_application_ref_unique UNIQUE (application_ref);
ALTER TABLE public.member ADD CONSTRAINT member_auth_user_id_unique UNIQUE (auth_user_id);
ALTER TABLE public.member ADD CONSTRAINT member_email_unique UNIQUE (email);
ALTER TABLE public.member_business_dna ADD CONSTRAINT member_business_dna_user_id_unique UNIQUE (user_id);
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_user_opp_unique UNIQUE (user_id, opportunity_id);
ALTER TABLE public.meta_tracking_config ADD CONSTRAINT meta_tracking_config_tenant_id_key UNIQUE (tenant_id);
ALTER TABLE public.meta_tracking_config ADD CONSTRAINT meta_tracking_config_tenant_uk UNIQUE (tenant_id);
ALTER TABLE public.monday_opportunity_registry ADD CONSTRAINT monday_opportunity_registry_tenant_id_product_id_key UNIQUE (tenant_id, product_id);
ALTER TABLE public.product_asset_intelligence ADD CONSTRAINT product_asset_intelligence_tenant_id_product_id_source_sour_key UNIQUE (tenant_id, product_id, source, source_ref);
ALTER TABLE public.product_market_evaluations ADD CONSTRAINT pme_unique UNIQUE (tenant_id, product_id, country_code, score_version);
ALTER TABLE public.product_market_platform_evaluations ADD CONSTRAINT ppf_unique UNIQUE (tenant_id, product_id, country_code, platform, score_version);
ALTER TABLE public.product_opportunity_decisions ADD CONSTRAINT product_opportunity_decisions_uq UNIQUE (tenant_id, product_id, country_code, score_version);
ALTER TABLE public.saved_opportunities ADD CONSTRAINT saved_opportunities_user_id_opportunity_id_key UNIQUE (user_id, opportunity_id);
ALTER TABLE public.spend_reservations ADD CONSTRAINT spend_reservations_idem UNIQUE (authority_id, idempotency_key);
ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE public.activation_authorizations ADD CONSTRAINT activation_authorizations_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_angles ADD CONSTRAINT ad_studio_angles_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_assets ADD CONSTRAINT ad_studio_assets_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_briefs ADD CONSTRAINT ad_studio_briefs_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_offers ADD CONSTRAINT ad_studio_offers_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_platform_variants ADD CONSTRAINT ad_studio_platform_variants_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_studio_static_creatives ADD CONSTRAINT ad_studio_static_creatives_pkey PRIMARY KEY (id);
ALTER TABLE public.analytics_events ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);
ALTER TABLE public.auth_event ADD CONSTRAINT auth_event_pkey PRIMARY KEY (id);
ALTER TABLE public.build_updates ADD CONSTRAINT build_updates_pkey PRIMARY KEY (id);
ALTER TABLE public.business_profiles ADD CONSTRAINT business_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_builder_drafts ADD CONSTRAINT campaign_builder_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_performance_snapshots ADD CONSTRAINT campaign_performance_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.cj_sourcing_requests ADD CONSTRAINT cj_sourcing_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_destination_choice ADD CONSTRAINT commerce_destination_choice_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_events ADD CONSTRAINT commerce_events_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_prediction_snapshots ADD CONSTRAINT commerce_prediction_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_store_connections ADD CONSTRAINT commerce_store_connections_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_store_projects ADD CONSTRAINT commerce_store_projects_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_supplier_products ADD CONSTRAINT commerce_supplier_products_pkey PRIMARY KEY (id);
ALTER TABLE public.commerce_tracking_identities ADD CONSTRAINT commerce_tracking_identities_pkey PRIMARY KEY (id);
ALTER TABLE public.communication_logs ADD CONSTRAINT communication_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.competitor_content ADD CONSTRAINT competitor_content_pkey PRIMARY KEY (id);
ALTER TABLE public.competitors ADD CONSTRAINT competitors_pkey PRIMARY KEY (id);
ALTER TABLE public.conversion_dispatch_ledger ADD CONSTRAINT conversion_dispatch_ledger_pkey PRIMARY KEY (id);
ALTER TABLE public.conversion_hero_variants ADD CONSTRAINT conversion_hero_variants_pkey PRIMARY KEY (variant);
ALTER TABLE public.conversion_section_types ADD CONSTRAINT conversion_section_types_pkey PRIMARY KEY (section_type);
ALTER TABLE public.conversion_template_families ADD CONSTRAINT conversion_template_families_pkey PRIMARY KEY (family);
ALTER TABLE public.daily_briefs ADD CONSTRAINT daily_briefs_pkey PRIMARY KEY (id);
ALTER TABLE public.demo_events ADD CONSTRAINT demo_events_pkey PRIMARY KEY (id);
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.discovery_state ADD CONSTRAINT discovery_state_pkey PRIMARY KEY (id);
ALTER TABLE public.ecommerce_market_universe ADD CONSTRAINT ecommerce_market_universe_pkey PRIMARY KEY (country_code);
ALTER TABLE public.engagement_patterns ADD CONSTRAINT engagement_patterns_pkey PRIMARY KEY (id);
ALTER TABLE public.founder_ecom_test_config ADD CONSTRAINT founder_ecom_test_config_pkey PRIMARY KEY (id);
ALTER TABLE public.founding_applications ADD CONSTRAINT founding_applications_pkey PRIMARY KEY (id);
ALTER TABLE public.fx_rates ADD CONSTRAINT fx_rates_pkey PRIMARY KEY (id);
ALTER TABLE public.generated_content ADD CONSTRAINT generated_content_pkey PRIMARY KEY (id);
ALTER TABLE public.growth_messages ADD CONSTRAINT growth_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.invitation ADD CONSTRAINT invitation_pkey PRIMARY KEY (id);
ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
ALTER TABLE public.market_price_observations ADD CONSTRAINT market_price_observations_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_authority_audit ADD CONSTRAINT marketing_authority_audit_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_campaign_drafts ADD CONSTRAINT marketing_campaign_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_campaign_executions ADD CONSTRAINT marketing_campaign_executions_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_spend_authority ADD CONSTRAINT marketing_spend_authority_pkey PRIMARY KEY (id);
ALTER TABLE public.media_assets ADD CONSTRAINT media_assets_pkey PRIMARY KEY (id);
ALTER TABLE public.media_image_jobs ADD CONSTRAINT media_image_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.media_job_costs ADD CONSTRAINT media_job_costs_pkey PRIMARY KEY (id);
ALTER TABLE public.media_providers ADD CONSTRAINT media_providers_pkey PRIMARY KEY (id);
ALTER TABLE public.media_video_jobs ADD CONSTRAINT media_video_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.media_video_scenes ADD CONSTRAINT media_video_scenes_pkey PRIMARY KEY (id);
ALTER TABLE public.member ADD CONSTRAINT member_pkey PRIMARY KEY (id);
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_pkey PRIMARY KEY (id);
ALTER TABLE public.member_business_dna ADD CONSTRAINT member_business_dna_pkey PRIMARY KEY (id);
ALTER TABLE public.member_feedback ADD CONSTRAINT member_feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.member_generated_content ADD CONSTRAINT member_generated_content_pkey PRIMARY KEY (id);
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_platform_config ADD CONSTRAINT meta_platform_config_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_tracking_config ADD CONSTRAINT meta_tracking_config_pkey PRIMARY KEY (id);
ALTER TABLE public.monday_opportunity_registry ADD CONSTRAINT monday_opportunity_registry_pkey PRIMARY KEY (id);
ALTER TABLE public.monday_opportunity_runs ADD CONSTRAINT monday_opportunity_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.opportunities ADD CONSTRAINT opportunities_pkey PRIMARY KEY (id);
ALTER TABLE public.pending_in_app_messages ADD CONSTRAINT pending_in_app_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.performance_experiments ADD CONSTRAINT performance_experiments_pkey PRIMARY KEY (id);
ALTER TABLE public.performance_learning_memory ADD CONSTRAINT performance_learning_memory_pkey PRIMARY KEY (id);
ALTER TABLE public.performance_learnings ADD CONSTRAINT performance_learnings_pkey PRIMARY KEY (id);
ALTER TABLE public.product_acquisitions ADD CONSTRAINT product_acquisitions_pkey PRIMARY KEY (id);
ALTER TABLE public.product_asset_intelligence ADD CONSTRAINT product_asset_intelligence_pkey PRIMARY KEY (id);
ALTER TABLE public.product_market_competitors ADD CONSTRAINT product_market_competitors_pkey PRIMARY KEY (id);
ALTER TABLE public.product_market_evaluations ADD CONSTRAINT product_market_evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.product_market_platform_evaluations ADD CONSTRAINT product_market_platform_evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.product_opportunity_decisions ADD CONSTRAINT product_opportunity_decisions_pkey PRIMARY KEY (id);
ALTER TABLE public.provider_capability_registry ADD CONSTRAINT provider_capability_registry_pkey PRIMARY KEY (source, evidence_category, market);
ALTER TABLE public.pulse_guide_events ADD CONSTRAINT pulse_guide_events_pkey PRIMARY KEY (id);
ALTER TABLE public.rejected_ideas ADD CONSTRAINT rejected_ideas_pkey PRIMARY KEY (id);
ALTER TABLE public.roadmap_items ADD CONSTRAINT roadmap_items_pkey PRIMARY KEY (id);
ALTER TABLE public.saved_opportunities ADD CONSTRAINT saved_opportunities_pkey PRIMARY KEY (id);
ALTER TABLE public.spend_reservations ADD CONSTRAINT spend_reservations_pkey PRIMARY KEY (id);
ALTER TABLE public.successful_opportunities ADD CONSTRAINT successful_opportunities_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_product_assets ADD CONSTRAINT supplier_product_assets_pkey PRIMARY KEY (id);
ALTER TABLE public.trend_clusters ADD CONSTRAINT trend_clusters_pkey PRIMARY KEY (id);
ALTER TABLE public.trend_signals ADD CONSTRAINT trend_signals_pkey PRIMARY KEY (id);
ALTER TABLE public.user_consent ADD CONSTRAINT user_consent_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_events ADD CONSTRAINT user_events_pkey PRIMARY KEY (id);
ALTER TABLE public.user_growth_profile ADD CONSTRAINT user_growth_profile_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_memory ADD CONSTRAINT user_memory_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.workflow_logs ADD CONSTRAINT workflow_logs_pkey PRIMARY KEY (id);
