-- STRATELOQ DR: production public CHECK constraints (schema baseline). NO data, NO secrets.
ALTER TABLE public.campaign_performance_snapshots ADD CONSTRAINT cps_level_chk CHECK ((level = ANY (ARRAY['CAMPAIGN'::text, 'ADSET'::text, 'AD'::text])));
ALTER TABLE public.campaign_performance_snapshots ADD CONSTRAINT cps_source_chk CHECK ((source_class = ANY (ARRAY['REAL_OBSERVED'::text, 'PLATFORM_REPORTED'::text, 'DERIVED'::text, 'ESTIMATED'::text, 'FIXTURE'::text, 'UNKNOWN'::text])));
ALTER TABLE public.commerce_destination_choice ADD CONSTRAINT commerce_destination_choice_destination_check CHECK ((destination = ANY (ARRAY['EXISTING_STORE'::text, 'PULSE_STORE'::text])));
ALTER TABLE public.commerce_prediction_snapshots ADD CONSTRAINT commerce_prediction_snapshots_visibility_check CHECK ((visibility = ANY (ARRAY['GLOBAL_SAFE'::text, 'TENANT_PRIVATE'::text])));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_content_context_check CHECK (((content_context IS NULL) OR (jsonb_typeof(content_context) = 'object'::text)));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_evidence_refs_check CHECK ((jsonb_typeof(evidence_refs) = 'array'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_factor_scores_check CHECK ((jsonb_typeof(factor_scores) = 'object'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_opportunity_class_check CHECK ((opportunity_class = ANY (ARRAY['high_potential'::text, 'emerging'::text, 'watch'::text, 'deprioritized'::text, 'insufficient_evidence'::text, 'AVOID'::text, 'WATCH'::text, 'TRENDING_WATCH'::text, 'STRONG_TEST'::text, 'HIGH_CONFIDENCE_TEST'::text, 'EXCEPTIONAL_TEST_CANDIDATE'::text, 'INSUFFICIENT_EVIDENCE'::text, 'VALIDATING'::text, 'WINNER'::text, 'IMPROVE'::text, 'STOP'::text])));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_overall_score_check CHECK (((overall_score IS NULL) OR ((overall_score >= 0) AND (overall_score <= 100))));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_positive_factors_check CHECK ((jsonb_typeof(positive_factors) = 'array'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_provenance_check CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_recommended_actions_check CHECK ((jsonb_typeof(recommended_actions) = 'array'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_recommended_decision_check CHECK (((recommended_decision IS NULL) OR (recommended_decision = ANY (ARRAY['TEST'::text, 'VALIDATE_FURTHER'::text, 'WATCH'::text, 'DEPRIORITIZE'::text, 'PREPARE_OFFER'::text, 'AVOID'::text, 'AVOID_PRODUCT_TRUST_BLOCKED'::text, 'AVOID_SUPPLIER_EXECUTION_FAIL'::text, 'GATHER_EVIDENCE'::text]))));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_risk_factors_check CHECK ((jsonb_typeof(risk_factors) = 'array'::text));
ALTER TABLE public.commerce_product_opportunities ADD CONSTRAINT commerce_product_opportunities_signal_refs_check CHECK ((jsonb_typeof(signal_refs) = 'array'::text));
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_destination_check CHECK ((destination = ANY (ARRAY['PULSE_STORE'::text, 'EXISTING_STORE'::text])));
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_source_kind_check CHECK ((source_kind = ANY (ARRAY['REAL'::text, 'FIXTURE'::text])));
ALTER TABLE public.commerce_product_pages ADD CONSTRAINT commerce_product_pages_status_check CHECK ((status = ANY (ARRAY['DRAFT'::text, 'GENERATING'::text, 'READY_FOR_REVIEW'::text, 'FAILED'::text, 'APPROVED'::text, 'PUBLISHED'::text, 'ARCHIVED'::text])));
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_extended_check CHECK (((extended IS NULL) OR (jsonb_typeof(extended) = 'object'::text)));
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_identity_basis_check CHECK ((identity_basis = ANY (ARRAY['canonical_url'::text, 'platform_id'::text, 'normalized_name'::text])));
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_provenance_check CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_role_valid CHECK ((product_role = ANY (ARRAY['own'::text, 'competitor'::text, 'candidate'::text])));
ALTER TABLE public.commerce_products ADD CONSTRAINT commerce_products_visibility_check CHECK ((visibility = ANY (ARRAY['GLOBAL_SAFE'::text, 'TENANT_PRIVATE'::text])));
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_evidence_check CHECK ((jsonb_typeof(evidence) = 'array'::text));
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_provenance_check CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_value_check CHECK (((value IS NULL) OR (jsonb_typeof(value) = 'object'::text)));
ALTER TABLE public.commerce_signals ADD CONSTRAINT commerce_signals_visibility_check CHECK ((visibility = ANY (ARRAY['GLOBAL_SAFE'::text, 'TENANT_PRIVATE'::text])));
ALTER TABLE public.commerce_store_connections ADD CONSTRAINT commerce_store_connections_connection_state_check CHECK ((connection_state = ANY (ARRAY['NOT_CONNECTED'::text, 'CONNECTING'::text, 'CONNECTED'::text, 'REAUTH_REQUIRED'::text, 'DISCONNECTED'::text, 'ERROR'::text])));
ALTER TABLE public.commerce_store_connections ADD CONSTRAINT commerce_store_connections_provider_check CHECK ((provider = ANY (ARRAY['SHOPIFY'::text, 'WOOCOMMERCE'::text, 'EXTERNAL_STORE'::text])));
ALTER TABLE public.commerce_store_connections ADD CONSTRAINT commerce_store_connections_visibility_check CHECK ((visibility = 'TENANT_PRIVATE'::text));
ALTER TABLE public.commerce_store_projects ADD CONSTRAINT commerce_store_projects_project_state_check CHECK ((project_state = ANY (ARRAY['DRAFT'::text, 'GENERATING'::text, 'READY_FOR_REVIEW'::text, 'FAILED'::text, 'APPROVED'::text, 'PUBLISHED'::text])));
ALTER TABLE public.commerce_store_projects ADD CONSTRAINT commerce_store_projects_source_kind_check CHECK ((source_kind = ANY (ARRAY['REAL'::text, 'FIXTURE'::text])));
ALTER TABLE public.communication_logs ADD CONSTRAINT communication_logs_channel_check CHECK ((channel = ANY (ARRAY['email'::text, 'slack'::text, 'sms'::text, 'in_app'::text])));
ALTER TABLE public.communication_logs ADD CONSTRAINT communication_logs_status_check CHECK ((status = ANY (ARRAY['sent'::text, 'delivered'::text, 'failed'::text, 'bounced'::text])));
ALTER TABLE public.conversion_dispatch_ledger ADD CONSTRAINT conversion_dispatch_ledger_consent_chk CHECK ((consent_state = ANY (ARRAY['GRANTED'::text, 'DENIED'::text, 'UNKNOWN'::text])));
ALTER TABLE public.conversion_dispatch_ledger ADD CONSTRAINT conversion_dispatch_ledger_state_chk CHECK ((state = ANY (ARRAY['RECEIVED'::text, 'VALIDATED'::text, 'QUEUED'::text, 'SENT'::text, 'ACCEPTED'::text, 'FAILED'::text, 'RETRYABLE'::text, 'REJECTED'::text, 'DEDUPLICATED'::text])));
ALTER TABLE public.demo_events ADD CONSTRAINT demo_events_event_type_check CHECK ((event_type = ANY (ARRAY['demo_started'::text, 'industry_selected'::text, 'opportunity_opened'::text, 'guide_question_clicked'::text, 'founding_member_clicked'::text, 'demo_completed'::text, 'screen_viewed'::text, 'explore_clicked'::text, 'back_clicked'::text, 'demo_closed'::text])));
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_commerce_inputs_object CHECK (((commerce_inputs IS NULL) OR (jsonb_typeof(commerce_inputs) = 'object'::text)));
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_entry_mode_valid CHECK (((entry_mode IS NULL) OR (entry_mode = ANY (ARRAY['existing_store'::text, 'no_store_yet'::text]))));
ALTER TABLE public.discovery_runs ADD CONSTRAINT discovery_runs_existing_store_requires_url CHECK (((entry_mode IS DISTINCT FROM 'existing_store'::text) OR (website IS NOT NULL)));
ALTER TABLE public.founder_ecom_test_config ADD CONSTRAINT one_row CHECK (id);
ALTER TABLE public.founding_applications ADD CONSTRAINT founding_applications_status_check CHECK ((status = ANY (ARRAY['new'::text, 'reviewing'::text, 'accepted'::text, 'rejected'::text, 'contacted'::text])));
ALTER TABLE public.fx_rates ADD CONSTRAINT fx_rates_rate_check CHECK ((rate > (0)::numeric));
ALTER TABLE public.invitation ADD CONSTRAINT invitation_status_check CHECK ((status = ANY (ARRAY['issued'::text, 'consumed'::text, 'expired'::text, 'revoked'::text])));
ALTER TABLE public.marketing_campaign_drafts ADD CONSTRAINT marketing_campaign_drafts_status_chk CHECK ((status = ANY (ARRAY['DRAFT'::text, 'READY_FOR_REVIEW'::text, 'APPROVED'::text, 'ARCHIVED'::text])));
ALTER TABLE public.marketing_campaign_executions ADD CONSTRAINT marketing_campaign_executions_status_check CHECK ((status = ANY (ARRAY['PENDING'::text, 'CREATED_PAUSED'::text, 'FAILED'::text, 'BLOCKED'::text])));
ALTER TABLE public.marketing_spend_authority ADD CONSTRAINT spend_authority_envelope CHECK (((spent + reserved) <= authorized_total));
ALTER TABLE public.marketing_spend_authority ADD CONSTRAINT spend_authority_nonneg CHECK (((authorized_total >= (0)::numeric) AND (spent >= (0)::numeric)));
ALTER TABLE public.marketing_spend_authority ADD CONSTRAINT spend_authority_reserved_nonneg CHECK ((reserved >= (0)::numeric));
ALTER TABLE public.marketing_spend_authority ADD CONSTRAINT spend_authority_status_chk CHECK ((status = ANY (ARRAY['DRAFT'::text, 'PENDING_APPROVAL'::text, 'ACTIVE'::text, 'EXHAUSTED'::text, 'EXPIRED'::text, 'REVOKED'::text, 'INACTIVE'::text])));
ALTER TABLE public.member ADD CONSTRAINT member_account_status_check CHECK ((account_status = ANY (ARRAY['active'::text, 'disabled'::text])));
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_provenance_object CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.member_actions ADD CONSTRAINT member_actions_status_canonical CHECK ((status = ANY (ARRAY['open'::text, 'done'::text, 'dismissed'::text])));
ALTER TABLE public.member_business_dna ADD CONSTRAINT member_business_dna_provenance_object CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.member_feedback ADD CONSTRAINT member_feedback_subject_type_check CHECK ((subject_type = ANY (ARRAY['opportunity'::text, 'content'::text])));
ALTER TABLE public.member_generated_content ADD CONSTRAINT member_generated_content_content_type_check CHECK ((content_type = ANY (ARRAY['SOCIAL_POST'::text, 'SHORT_VIDEO_SCRIPT'::text, 'LONG_VIDEO_SCRIPT'::text])));
ALTER TABLE public.member_generated_content ADD CONSTRAINT member_generated_content_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'processing'::text, 'ready'::text, 'failed'::text])));
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_mode_check CHECK (((opportunity_id IS NOT NULL) OR ((NULLIF(btrim(COALESCE(title, ''::text)), ''::text) IS NOT NULL) AND (rank IS NOT NULL) AND (evidence IS NOT NULL) AND (jsonb_typeof(evidence) = 'array'::text) AND (evidence <> '[]'::jsonb))));
ALTER TABLE public.member_opportunities ADD CONSTRAINT member_opportunities_provenance_object CHECK ((jsonb_typeof(provenance) = 'object'::text));
ALTER TABLE public.meta_platform_config ADD CONSTRAINT meta_platform_config_singleton CHECK ((id = 1));
ALTER TABLE public.meta_tracking_config ADD CONSTRAINT meta_tracking_config_verif_state_chk CHECK ((verification_state = ANY (ARRAY['UNVERIFIED'::text, 'VERIFIED'::text, 'FAILED'::text, 'ERROR'::text])));
ALTER TABLE public.performance_experiments ADD CONSTRAINT perf_exp_status_chk CHECK ((status = ANY (ARRAY['DRAFT'::text, 'RUNNING'::text, 'COMPLETED'::text, 'ABANDONED'::text, 'INSUFFICIENT_EVIDENCE'::text])));
ALTER TABLE public.performance_learnings ADD CONSTRAINT perf_learn_conf_chk CHECK ((confidence = ANY (ARRAY['NONE'::text, 'LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'FIXTURE_NONE'::text])));
ALTER TABLE public.performance_learnings ADD CONSTRAINT perf_learn_type_chk CHECK ((learning_type = ANY (ARRAY['OBSERVATION'::text, 'DERIVED_FINDING'::text, 'HYPOTHESIS'::text, 'RECOMMENDATION'::text])));
ALTER TABLE public.product_acquisitions ADD CONSTRAINT product_acquisitions_state_check CHECK ((state = ANY (ARRAY['DISCOVERED'::text, 'SOURCED'::text, 'SELECTED'::text, 'PREPARING'::text, 'READY_FOR_REVIEW'::text, 'APPROVED'::text, 'EXPORTED'::text, 'PREPARE_FAILED'::text, 'EXPORT_FAILED'::text, 'DISCARDED'::text, 'IMPORTED'::text, 'IMPORT_FAILED'::text])));
ALTER TABLE public.product_market_competitors ADD CONSTRAINT pmcomp_country_chk CHECK ((country_code ~ '^[A-Z]{2}$'::text));
ALTER TABLE public.product_market_competitors ADD CONSTRAINT pmcomp_match_chk CHECK ((match_class = ANY (ARRAY['EXACT_PRODUCT'::text, 'CLOSE_COMPARABLE'::text, 'CATEGORY_COMPETITOR'::text, 'UNRELATED'::text])));
ALTER TABLE public.product_market_evaluations ADD CONSTRAINT pme_conf_chk CHECK ((evidence_confidence = ANY (ARRAY['NONE'::text, 'LOW'::text, 'MEDIUM'::text, 'HIGH'::text])));
ALTER TABLE public.product_market_evaluations ADD CONSTRAINT pme_country_chk CHECK ((country_code ~ '^[A-Z]{2}$'::text));
ALTER TABLE public.product_market_evaluations ADD CONSTRAINT pme_decision_chk CHECK ((market_decision = ANY (ARRAY['TEST'::text, 'WATCH'::text, 'AVOID'::text])));
ALTER TABLE public.product_market_platform_evaluations ADD CONSTRAINT ppf_country_chk CHECK ((country_code ~ '^[A-Z]{2}$'::text));
ALTER TABLE public.product_market_platform_evaluations ADD CONSTRAINT ppf_platform_chk CHECK ((platform = ANY (ARRAY['FACEBOOK'::text, 'INSTAGRAM'::text, 'TIKTOK'::text, 'GOOGLE_SEARCH'::text])));
ALTER TABLE public.product_market_platform_evaluations ADD CONSTRAINT ppf_rec_chk CHECK ((recommendation = ANY (ARRAY['PRIMARY_TEST'::text, 'SECONDARY_TEST'::text, 'ALTERNATIVE'::text, 'WATCH'::text, 'INSUFFICIENT_EVIDENCE'::text, 'AVOID'::text])));
ALTER TABLE public.provider_capability_registry ADD CONSTRAINT provider_capability_registry_availability_check CHECK ((availability = ANY (ARRAY['AVAILABLE'::text, 'PARTIAL'::text, 'SOURCE_UNSUPPORTED'::text, 'SOURCE_BLOCKED'::text, 'TEMPORARILY_UNAVAILABLE'::text, 'UNKNOWN'::text])));
ALTER TABLE public.roadmap_items ADD CONSTRAINT roadmap_items_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'building'::text, 'released'::text, 'paused'::text])));
ALTER TABLE public.spend_reservations ADD CONSTRAINT spend_reservations_amt_pos CHECK ((amount > (0)::numeric));
