-- STRATELOQ DR: production public non-constraint indexes (schema baseline). NO data, NO secrets.
-- (PK/UNIQUE-backed indexes are created implicitly by constraints_pk_unique.sql.)
CREATE INDEX idx_asangles_brief ON public.ad_studio_angles USING btree (brief_id);
CREATE INDEX idx_asbriefs_tenant ON public.ad_studio_briefs USING btree (tenant_id);
CREATE INDEX idx_asvariants_angle ON public.ad_studio_platform_variants USING btree (angle_id);
CREATE INDEX idx_analytics_user_date ON public.analytics_events USING btree (user_id, occurred_at DESC);
CREATE UNIQUE INDEX business_profiles_application_id_unique ON public.business_profiles USING btree (application_id);
CREATE INDEX idx_cb_drafts_tenant ON public.campaign_builder_drafts USING btree (tenant_id);
CREATE INDEX cps_exec_idx ON public.campaign_performance_snapshots USING btree (campaign_execution_id);
CREATE INDEX cps_tenant_idx ON public.campaign_performance_snapshots USING btree (tenant_id, platform, level);
CREATE UNIQUE INDEX uq_cj_sourcing_open_concept_market ON public.cj_sourcing_requests USING btree (lower(product_concept), target_market) WHERE (status = ANY (ARRAY['SUBMITTED'::text, 'PENDING'::text, 'PENDING_EXTERNAL_CJ_SOURCING'::text, 'SOURCED'::text]));
CREATE INDEX idx_commerce_events_campaign ON public.commerce_events USING btree (tenant_id, campaign_id, event_name);
CREATE UNIQUE INDEX uq_commerce_purchase_order ON public.commerce_events USING btree (tenant_id, order_id) WHERE ((event_name = 'PURCHASE'::text) AND (order_id IS NOT NULL));
CREATE UNIQUE INDEX cps_idem ON public.commerce_prediction_snapshots USING btree (user_id, product_id, target_market, evidence_version);
CREATE INDEX cps_product_idx ON public.commerce_prediction_snapshots USING btree (product_id, target_market);
CREATE INDEX cpo_product_idx ON public.commerce_product_opportunities USING btree (product_id);
CREATE UNIQUE INDEX cpo_tenant_market_unique ON public.commerce_product_opportunities USING btree (user_id, product_id, COALESCE(target_market, '__GLOBAL__'::text)) WHERE (source_run_id IS NULL);
CREATE INDEX cpo_user_rank_idx ON public.commerce_product_opportunities USING btree (user_id, source_run_id, rank);
CREATE INDEX commerce_products_run_idx ON public.commerce_products USING btree (source_run_id);
CREATE INDEX commerce_products_user_idx ON public.commerce_products USING btree (user_id, last_observed_at DESC);
CREATE INDEX commerce_signals_product_idx ON public.commerce_signals USING btree (product_id);
CREATE INDEX commerce_signals_run_idx ON public.commerce_signals USING btree (source_run_id);
CREATE INDEX commerce_signals_user_idx ON public.commerce_signals USING btree (user_id, observed_at DESC);
CREATE UNIQUE INDEX csc_user_provider_domain_uidx ON public.commerce_store_connections USING btree (user_id, provider, COALESCE(store_domain, ''::text));
CREATE INDEX idx_commerce_supplier_products_category ON public.commerce_supplier_products USING btree (lower(category));
CREATE INDEX idx_commerce_supplier_products_sku ON public.commerce_supplier_products USING btree (sku);
CREATE INDEX idx_tracking_ident_campaign ON public.commerce_tracking_identities USING btree (campaign_id);
CREATE INDEX idx_competitor_content_competitor ON public.competitor_content USING btree (competitor_id, published_at DESC);
CREATE INDEX idx_competitors_user ON public.competitors USING btree (user_id);
CREATE INDEX conversion_dispatch_ledger_retry_idx ON public.conversion_dispatch_ledger USING btree (state) WHERE (state = ANY (ARRAY['RETRYABLE'::text, 'QUEUED'::text]));
CREATE INDEX conversion_dispatch_ledger_tenant_idx ON public.conversion_dispatch_ledger USING btree (tenant_id, provider, state);
CREATE INDEX idx_daily_briefs_user ON public.daily_briefs USING btree (user_id, date DESC);
CREATE UNIQUE INDEX founding_applications_work_email_unique ON public.founding_applications USING btree (lower(work_email));
CREATE INDEX idx_generated_content_opp ON public.generated_content USING btree (opportunity_id);
CREATE INDEX idx_generated_content_user ON public.generated_content USING btree (user_id, generated_at DESC);
CREATE INDEX idx_growth_messages_agent ON public.growth_messages USING btree (agent, sent_at DESC);
CREATE INDEX idx_growth_messages_ratelimit ON public.growth_messages USING btree (user_id, agent, sent_at DESC);
CREATE INDEX idx_growth_messages_user ON public.growth_messages USING btree (user_id, sent_at DESC);
CREATE UNIQUE INDEX invitation_one_active_issued_per_application ON public.invitation USING btree (application_ref) WHERE (status = 'issued'::text);
CREATE INDEX invitation_status_expires_at_idx ON public.invitation USING btree (status, expires_at);
CREATE INDEX leads_created_at_idx ON public.leads USING btree (created_at DESC);
CREATE INDEX leads_email_idx ON public.leads USING btree (email);
CREATE INDEX leads_market_idx ON public.leads USING btree (market);
CREATE INDEX idx_mpo_query_market ON public.market_price_observations USING btree (lower(product_query), market, observed_at DESC);
CREATE INDEX idx_authority_audit_tenant ON public.marketing_authority_audit USING btree (tenant_id, created_at DESC);
CREATE INDEX idx_mcd_created ON public.marketing_campaign_drafts USING btree (created_at DESC);
CREATE INDEX idx_mcd_run ON public.marketing_campaign_drafts USING btree (source_run_id);
CREATE INDEX idx_mcd_status ON public.marketing_campaign_drafts USING btree (status);
CREATE INDEX idx_mcd_user ON public.marketing_campaign_drafts USING btree (user_id);
CREATE INDEX idx_spend_authority_tenant ON public.marketing_spend_authority USING btree (tenant_id);
CREATE INDEX idx_media_assets_tenant ON public.media_assets USING btree (tenant_id);
CREATE INDEX idx_media_image_jobs_tenant ON public.media_image_jobs USING btree (tenant_id);
CREATE INDEX idx_media_video_jobs_tenant ON public.media_video_jobs USING btree (tenant_id);
CREATE INDEX member_feedback_user_idx ON public.member_feedback USING btree (user_id, created_at DESC);
CREATE INDEX member_generated_content_run_rank_type_idx ON public.member_generated_content USING btree (user_id, source_run_id, rank, content_type);
CREATE INDEX member_generated_content_user_created_idx ON public.member_generated_content USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX member_opportunities_run_rank_uidx ON public.member_opportunities USING btree (source_run_id, rank) WHERE (source_run_id IS NOT NULL);
CREATE INDEX idx_opportunities_created ON public.opportunities USING btree (created_at DESC);
CREATE INDEX idx_opportunities_platform ON public.opportunities USING btree (best_platform);
CREATE INDEX idx_opportunities_score ON public.opportunities USING btree (opportunity_score DESC);
CREATE INDEX idx_opportunities_status ON public.opportunities USING btree (status);
CREATE INDEX opportunities_status_score_idx ON public.opportunities USING btree (status, opportunity_score DESC);
CREATE INDEX idx_pending_messages_user ON public.pending_in_app_messages USING btree (user_id, seen_at);
CREATE INDEX perf_exp_tenant_idx ON public.performance_experiments USING btree (tenant_id, is_fixture, status);
CREATE INDEX perf_mem_tenant_idx ON public.performance_learning_memory USING btree (tenant_id, product_id, is_fixture);
CREATE INDEX perf_learn_snapshot_idx ON public.performance_learnings USING btree (performance_snapshot_id);
CREATE INDEX perf_learn_tenant_idx ON public.performance_learnings USING btree (tenant_id, is_fixture, learning_type);
CREATE UNIQUE INDEX product_acquisitions_active_product_uidx ON public.product_acquisitions USING btree (user_id, source_run_id, COALESCE((winning_product_snapshot ->> 'product_url'::text), (winning_product_snapshot ->> 'product_title'::text))) WHERE (state <> 'DISCARDED'::text);
CREATE INDEX product_acquisitions_user_created_idx ON public.product_acquisitions USING btree (user_id, created_at DESC);
CREATE INDEX product_acquisitions_user_run_idx ON public.product_acquisitions USING btree (user_id, source_run_id);
CREATE INDEX idx_pai_product ON public.product_asset_intelligence USING btree (tenant_id, product_id);
CREATE INDEX pmcomp_pm_idx ON public.product_market_competitors USING btree (tenant_id, product_id, country_code);
CREATE INDEX pmcomp_pme_idx ON public.product_market_competitors USING btree (product_market_evaluation_id);
CREATE INDEX pme_rank_idx ON public.product_market_evaluations USING btree (tenant_id, product_id, market_opportunity_score DESC);
CREATE INDEX pme_tenant_product_idx ON public.product_market_evaluations USING btree (tenant_id, product_id);
CREATE INDEX ppf_pm_idx ON public.product_market_platform_evaluations USING btree (tenant_id, product_id, country_code);
CREATE INDEX idx_pod_pme ON public.product_opportunity_decisions USING btree (product_market_evaluation_id);
CREATE INDEX idx_pod_tenant_product ON public.product_opportunity_decisions USING btree (tenant_id, product_id);
CREATE INDEX idx_spa_primary ON public.supplier_product_assets USING btree (supplier, supplier_product_id, is_primary);
CREATE INDEX idx_spa_product ON public.supplier_product_assets USING btree (supplier, supplier_product_id);
CREATE INDEX idx_trend_clusters_score ON public.trend_clusters USING btree (trend_score DESC);
CREATE INDEX idx_trend_clusters_updated ON public.trend_clusters USING btree (updated_at DESC);
CREATE INDEX trend_clusters_trend_score_updated_idx ON public.trend_clusters USING btree (trend_score DESC, updated_at DESC);
CREATE INDEX idx_trend_signals_collected ON public.trend_signals USING btree (collected_at DESC);
CREATE INDEX idx_trend_signals_region ON public.trend_signals USING btree (region);
CREATE INDEX idx_trend_signals_source ON public.trend_signals USING btree (source);
CREATE INDEX trend_signals_collected_at_idx ON public.trend_signals USING btree (collected_at DESC);
CREATE INDEX idx_user_events_category ON public.user_events USING btree (event_category);
CREATE INDEX idx_user_events_retention ON public.user_events USING btree (retention_until);
CREATE INDEX idx_user_events_type ON public.user_events USING btree (event_type, occurred_at DESC);
CREATE INDEX idx_user_events_user ON public.user_events USING btree (user_id, occurred_at DESC);
CREATE INDEX idx_growth_profile_activation ON public.user_growth_profile USING btree (activation_status);
CREATE INDEX idx_growth_profile_churn ON public.user_growth_profile USING btree (churn_risk_tier);
CREATE INDEX idx_growth_profile_signup ON public.user_growth_profile USING btree (days_since_signup);
CREATE INDEX idx_growth_profile_upgrade ON public.user_growth_profile USING btree (upgrade_propensity_tier);
CREATE INDEX idx_user_memory_type ON public.user_memory USING btree (memory_type);
CREATE INDEX idx_user_memory_user ON public.user_memory USING btree (user_id);
CREATE INDEX idx_workflow_logs_agent ON public.workflow_logs USING btree (agent, created_at DESC);
CREATE INDEX idx_workflow_logs_status ON public.workflow_logs USING btree (status);
